Repository benchttp/runner, pull requests merged in 2022-02, with the labels that each got.

#23 feat: implement request tracer
  README.md
  cmd/runner/main.go
  requester/requester.go
  requester/tracer.go
  requester/tracer_internal_test.go
Labels: must have

#28 fix: zero-values cli flags do not override config file
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/default.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  config/file/raw.go
  go.mod
  go.sum
  test/testdata/config/benchttp-zeros.yml
Labels: bug

#29 feat: implement proper error handling for requester
  cmd/runner/main.go
  config/config.go
  dispatcher/dispatcher.go
  dispatcher/dispatcher_test.go
  requester/error.go
  requester/report.go
  requester/requester.go
  requester/requester_internal_test.go
  semimpl/do.go
Labels: must have

#39 fix: test requester.TestTracer occasionally fails
  requester/tracer_internal_test.go
Labels: bug

#40 feat: implement config option interval
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/field.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  requester/requester.go
  requester/requester_internal_test.go
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: enhancement, must have

#42 ci: unit test config file parsing errors
  cmd/runner/main.go
  config/file/error.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  config/file/parser_internal_test.go
  test/testdata/config/badext.yams
  test/testdata/config/badfields.json
  test/testdata/config/badfields.yml
  test/testdata/config/benchttp.yaml
Labels: enhancement

#43 Feat/add config option request body
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/default.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  requester/error.go
  requester/requester.go
  requester/requester_internal_test.go
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: must have

#45 feat(ux): implement live feedback
  Makefile
  ansi/style.go
  cmd/runner/main.go
  dispatcher/dispatcher.go
  dispatcher/dispatcher_test.go
  requester/print.go
  requester/requester.go
Labels: enhancement, nice to have

#49 dev: refactor config responsibilities
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/default.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  config/file/parser_internal_test.go
  requester/error.go
  requester/print.go
  requester/report.go
  requester/requester.go
  requester/requester_internal_test.go
  test/testdata/config/badfields.json
  test/testdata/config/badfields.yml
  test/testdata/config/benchttp-zeros.yml
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: enhancement

#56 bug: huge trace
  config/file/parser.go
  requester/error.go
  requester/httputil.go
  requester/print.go
  requester/report.go
  requester/requester.go
  requester/requester_internal_test.go
  requester/tracer.go
  requester/tracer_internal_test.go
Labels: bug

#51 feat(output): implement output strategies
  .gitignore
  ansi/style.go
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/parser.go
  config/output.go
  config/output_test.go
  output/endpoint.go
  output/endpoint_prod.go
  output/error.go
  output/export/export.go
  output/output.go
  output/strategy.go
  requester/report.go
  requester/requester.go
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: must have

#58 feat(output): silent mode
  .golangci.yml
  cmd/runner/main.go
  config/config.go
  config/config_test.go
  config/default.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  output/output.go
  requester/requester.go
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: nice to have

#57 feat(output): user-defined template
  cmd/runner/main.go
  config/config.go
  config/field.go
  config/field_test.go
  config/file/parse.go
  config/file/parse_test.go
  output/error.go
  output/output.go
  test/testdata/config/benchttp.json
  test/testdata/config/benchttp.yaml
  test/testdata/config/benchttp.yml
Labels: nice to have

#65 feat: handle graceful shutdown on os.Interrupt
  cmd/runner/main.go
  requester/error.go
  requester/print.go
  requester/requester.go
  requester/requester_internal_test.go
Labels: enhancement

#66 feat: extend config files
  config/file/error.go
  config/file/find_test.go
  config/file/parse.go
  config/file/parse_test.go
  config/file/testdata/extends/extends-circular-0.yml
  config/file/testdata/extends/extends-circular-1.yml
  config/file/testdata/extends/extends-circular-2.yml
  config/file/testdata/extends/extends-circular-self.yml
  config/file/testdata/extends/extends-valid-child.yml
  config/file/testdata/extends/extends-valid-parent.yml
  config/file/testdata/extends/nest-0/nest-1/extends-valid-nested.yml
  config/file/testdata/invalid/badext.yams
  config/file/testdata/invalid/badfields.json
  config/file/testdata/invalid/badfields.yml
  config/file/testdata/valid/benchttp-zeros.yml
  config/file/testdata/valid/benchttp.json
  config/file/testdata/valid/benchttp.yaml
  config/file/testdata/valid/benchttp.yml
Labels: nice to have

#72 fix: use new endpoint
  config/file/parse_test.go
  config/file/testdata/valid/benchttp.json
  config/file/testdata/valid/benchttp.yaml
  config/file/testdata/valid/benchttp.yml
  output/endpoint.go
  output/endpoint_prod.go
  output/export/export.go
  output/report.go
  requester/benchmark.go
  requester/requester.go
  requester/requester_internal_test.go
Labels: bug

#73 dev: write unit tests for package output
  output/error.go
  output/export/export.go
  output/export/export_test.go
  output/report.go
  output/report_test.go
  output/strategy.go
  output/strategy_internal_test.go
  requester/benchmark.go
Labels: enhancement

#74 ops: create cross-platforms build script
  Makefile
  script/build
Labels: must have
